### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by qingyunha** [7WebPages/snakepit-game#6]
```
$ python3 server.py                                                                                       
Traceback (most recent call last):
  File "server.py", line 7, in <module>
    from game import Game
  File "/tmp/snakepit-game/game.py", line 5, in <module>
    from player import Player
  File "/tmp/snakepit-game/player.py", line 5, in <module>
    from datatypes import Vector, Position, Draw
  File "/tmp/snakepit-game/datatypes.py", line 9
    Draw = namedtuple("Draw",  "x y char color"])
                                               ^
SyntaxError: invalid syntax
```

**Comment by kirrx** [comment]
thanks for noticing
